# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopingListProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

  # Pods for ShopingListProject

end
